[Writable]
LogLevel = 'INFO'
    [Writable.StoreAndForward]
    Enabled = true
    RetryInterval = '5s'
    MaxRetryCount = 0

[Service]
BootTimeout = '30s'
ClientMonitor = '15s'
CheckInterval = '10s'
Host = 'localhost'
Port = 48095
Protocol = 'http'
ReadMaxLimit = 100
StartupMsg = 'This is a sample Filter/XML/MQTT Transform Application Service'
Timeout = '30s'

[Registry]
Host = 'edgex-core-consul'
Port = 8500
Type = 'consul'

[Logging]
EnableRemote = false
File = './logs/simple-filter-xml-mqtt.log'

# Database is require when Store and Forward is enabled
[Database]
Type = "redisdb"
Host = "edgex-redis"
Port = 6379
Timeout = "30s"
Username = ""
Password = ""

[Clients]
  [Clients.CoreData]
  Protocol = 'http'
  Host = 'edgex-core-data'
  Port = 48080

  [Clients.Logging]
  Protocol = "http"
  Host = "edgex-support-logging"
  Port = 48061

[MessageBus]
Type = 'zero'
    [MessageBus.PublishHost]
        Host = '*'
        Port = 5564
        Protocol = 'tcp'
    [MessageBus.SubscribeHost]
        Host = 'edgex-core-data'
        Port = 5563
        Protocol = 'tcp'

[Binding]
Type="messagebus"
SubscribeTopic="events"
PublishTopic="somewhere"

[ApplicationSettings]
ApplicationName = "konnekt-app-functions-service"
# Default  MQTT Config
MqttAddress = "mosquitto"
MqttPort = "1883"
MqttProtocol = "tcp"
MqttTopic = "appf"
MqttUser = ""
MqttPassword =  ""
